// => LOAD
export const BUSINESS_START_LOAD = 'BUSINESS_START_LOAD'
export const BUSINESS_FINISH_LOAD = 'BUSINESS_FINISH_LOAD'
// => LOAD

// => PROJECTS
export const BUSINESS_GET_PROJECTS = 'BUSINESS_GET_PROJECTS'
// => PROJECTS
